remove action, hard code script

diff --git a/.github/workflows/update_metrics.yaml b/.github/workflows/update_metrics.yaml
--- a/.github/workflows/update_metrics.yaml
+++ b/.github/workflows/update_metrics.yaml
@@ -34,6 +34,32 @@ jobs:
       run: |
         python main.py
     - name: Push updated index.json
-      uses: mikeal/publish-to-github-action@master
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        # check values
+        if [ -z "${GITHUB_TOKEN}" ]; then
+            echo "error: not found GITHUB_TOKEN"
+            exit 1
+        fi
+
+        if [ -z "${BRANCH_NAME}" ]; then
+           export BRANCH_NAME=main
+        fi
+
+        # initialize git
+        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
+        git config http.sslVerify false
+        git config user.name "Automated Publisher"
+        git config user.email "actions@users.noreply.github.com"
+        git remote add publisher "${remote_repo}"
+        git show-ref # useful for debugging
+        git branch --verbose
+
+        # publish any new files
+        git checkout ${BRANCH_NAME}
+        git add -A
+        timestamp=$(date -u)
+        git commit -m "Automated publish: ${timestamp} ${GITHUB_SHA}" || exit 0
+        git pull --rebase publisher ${BRANCH_NAME}
+        git push publisher ${BRANCH_NAME}
